version: '2'
services:
  zoo1:
      image: zookeeper:3.4
      ports:
          - 2181:2181
      environment:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
      image: zookeeper:3.4
      ports:
          - 2182:2181
      environment:
          ZOO_MY_ID: 2
          ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
      image: zookeeper:3.4
      ports:
          - 2183:2181
      environment:
          ZOO_MY_ID: 3
          ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"

    environment:
      # - ZOOKEEPER_CONNECTION_STRING:zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      ZOOKEEPER_IP: zoo1
      ZOOKEEPER_PORT: 2181

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zoo1:2181
      APPLICATION_SECRET: lemein

# networks:
#   kafka-net:
#     driver: bridge
